[change] [proposed by Jpse-Marcio Martins] no more check the OSYTE, check if functions file exists instead
git-svn-id: https://subversion.renater.fr/sympa/trunk@6050 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/src/etc/script/sympa.in b/src/etc/script/sympa.in
--- a/src/etc/script/sympa.in
+++ b/src/etc/script/sympa.in
@@ -14,6 +14,19 @@
 # chkconfig: 345 95 05
 # description: sympa is a powerfull mailing lists management system.
 
+if [ -f --initdir--/functions ]; then
+    # Source function library.
+    . --initdir--/functions
+    
+    ## Set a flag 
+    use_functions=1
+fi
+
+if [ -f /etc/sysconfig/network ]; then
+    # Get config.
+    . /etc/sysconfig/network
+fi
+
 # OSTYPE is not defined on Solaris
 if [ ! "${OSTYPE}" ]; then
     OSTYPE=`uname -s`
@@ -36,14 +49,6 @@ fi
 
 if [ -f /etc/slackware-version ] ; then
     OSTYPE='Slack'
-fi
-
-if [ ${OSTYPE} != "Slack" -a ${OSTYPE} != "FreeBSD" -a ${OSTYPE} != "SunOS" -a ${OSTYPE} != "darwin7.0" -a ${OSTYPE} != "Debian" -a ${OSTYPE} != "Suse" ]; then
-    # Source function library.
-    . --initdir--/functions
-
-    # Get config.
-    . /etc/sysconfig/network
 fi
 
 # Sympa parameters
@@ -71,7 +76,7 @@ sympa_status() {
         return 1
     fi
  
-    if [ ${OSTYPE} != "Slack" -a ${OSTYPE} != "FreeBSD" -a ${OSTYPE} != "SunOS" -a ${OSTYPE} != "darwin7.0"  -a ${OSTYPE} != "Debian" -a ${OSTYPE} != "Suse" -a ${OSTYPE} != "linux" -a ${OSTYPE} != "linux-gnu" ]; then
+    if [ ${use_functions} ]; then
 
       status $1.pl
 
@@ -108,10 +113,10 @@ sympa_module_start() {
 #		startparam=""
 #	fi
  
-	if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
-		$sympadir/$1.pl $startparam && echo "success" || echo "failure"
-	else
+	if [ ${use_functions} ]; then
 		$sympadir/$1.pl $startparam && success || failure
+	else
+		$sympadir/$1.pl $startparam && echo "success" || echo "failure"
 	fi
 	echo
 }
@@ -128,24 +133,10 @@ sympa_start() {
 		3)
 			echo $echo_opt "Starting module $1.pl: "
 			sympa_module_start $1
-			if [ ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" ]; then
-				if [ $? -eq 0 ]; then
-        	                       	echo "$1.pl started: success"
-	                       	else
-                	               	echo "$1.pl not started: failure"
-                       		fi
-			fi
 			;;
 		1) 
 			echo $echo_opt "Starting $1, overwriting old pid file."
 			sympa_module_start $1
-			if [ ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" ]; then
-				if [ $? -eq 0 ]; then
-        	                       	echo "$1.pl started: success"
-	                       	else
-                	               	echo "$1.pl not started: failure"
-                       		fi
-			fi
 			;;
 		0)
 			echo "$1 seems active. No action will be taken."
@@ -166,17 +157,17 @@ sympa_stop() {
 		pid=`head -1 --piddir--/$1.pid`
 		running=`ps -A | grep "$pid"`
 		if [ $1 == 'bulk' ]; then
-		    if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
-			kill -TERM $pid && echo "success" || echo "failure"
-		    else
+		    if [ ${use_functions} ]; then
 			kill -TERM $pid && success || failure
+		    else
+			kill -TERM $pid && echo "success" || echo "failure"
 		    fi		    
 		else 
 		    if [ "$running" != "" ]; then
-			if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
-			    kill -TERM $pid && echo "success" || echo "failure"
-			else
+			if [ ${use_functions} ]; then
 			    kill -TERM $pid && success || failure
+			else
+			    kill -TERM $pid && echo "success" || echo "failure"
 			fi		    
 
 		    else
