[feature] "sympa.pl --health_check" checks config files, database connection and structure, and data structure version.  It is invoked at first time in sympa init script and reports errors if any. Instead, daemons such as sympa.pl no longer check database structure nor data version.
git-svn-id: https://subversion.renater.fr/sympa/branches/sympa-6.2-branch@10897 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/src/etc/script/sympa.in b/src/etc/script/sympa.in
--- a/src/etc/script/sympa.in
+++ b/src/etc/script/sympa.in
@@ -12,7 +12,7 @@
 # Modified by Michel Bouissou  27/07/2000
 #
 # chkconfig: 345 95 05
-# description: sympa is a powerfull mailing lists management system.
+# description: Sympa is a powerful mailing list management system.
 
 if [ -f --initdir--/functions ]; then
     # Source function library.
@@ -103,6 +103,24 @@ sympa_status() {
         echo "$1 is stopped."
         return 3
     fi
+}
+
+# Health check
+sympa_check() {
+	echo $echo_opt "Checking environment: "
+	if [ ${use_functions} ]; then
+		$sympadir/sympa.pl --health_check && success || failure
+		return $?
+	else
+		if $sympadir/sympa.pl --health_check; then
+			echo "success"
+			return 0
+		else
+			echo "failure"
+			return 1
+		fi
+	fi
+        echo
 }
 
 # Start a module
@@ -225,6 +243,7 @@ case "$1" in
   start)
 	if [ ! -f ${sympalockdir}/sympa ]; then
 		echo "Starting Sympa subsystem: "
+		sympa_check || exit 1
 		sympa_start sympa
 		sympa_start bulk
 		sympa_start archived
