[feature] The bulk mailer is now separated into two different categories of processes: master and slave. When lauched, only one bulk mailer process runs : the master. If the number of packets to be sent grows too large, it forks to several slave processes, that will auto-destroy after some time. four parameters are used:
- bulk_fork_threshold	the number of waiting packets that, once reached, triggers the slaves creation

- bulk_max_count	the total number of bulk processes allowed.

- bulk_ttl		the time to live for slave processes (in seconds)

- bulk_wait_to_fork	the number of seconds that elapse before the master bulk process check if the number of packet is too large and slave creation is neccessary. Note the this check implies a query to the database.



git-svn-id: https://subversion.renater.fr/sympa/trunk@5662 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/src/etc/script/sympa b/src/etc/script/sympa
--- a/src/etc/script/sympa
+++ b/src/etc/script/sympa
@@ -165,14 +165,23 @@ sympa_stop() {
 		echo $echo_opt "Stopping module $1.pl: "
 		pid=`head -1 --PIDDIR--/$1.pid`
 		running=`ps -A | grep "$pid"`
-		if [ "$running" != "" ]; then
-		if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
+		if [ $1 == 'bulk' ]; then
+		    if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
 			kill -TERM $pid && echo "success" || echo "failure"
 		    else
 			kill -TERM $pid && success || failure
 		    fi		    
-		else
-		    echo "died"
+		else 
+		    if [ "$running" != "" ]; then
+			if [ ${OSTYPE} = "Slack" -o ${OSTYPE} = "IRIX" -o ${OSTYPE} = "SunOS" -o ${OSTYPE} = "Debian" -o ${OSTYPE} = "Suse" ]; then
+			    kill -TERM $pid && echo "success" || echo "failure"
+			else
+			    kill -TERM $pid && success || failure
+			fi		    
+
+		    else
+			echo "died"
+		    fi
 		fi
 		echo
 	else
