[feature] "sympa.pl --health_check" checks config files, database connection and structure, and data structure version.  It is invoked at first time in sympa init script and reports errors if any. Instead, daemons such as sympa.pl no longer check database structure nor data version.
git-svn-id: https://subversion.renater.fr/sympa/branches/sympa-6.2-branch@8795 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/src/etc/script/sympa.in b/src/etc/script/sympa.in
--- a/src/etc/script/sympa.in
+++ b/src/etc/script/sympa.in
@@ -105,6 +105,24 @@ sympa_status() {
     fi
 }
 
+# Health check
+sympa_check() {
+	echo $echo_opt "Checking environment: "
+	if [ ${use_functions} ]; then
+		$sympadir/sympa.pl --health_check && success || failure
+		return $?
+	else
+		if $sympadir/sympa.pl --health_check; then
+			echo "success"
+			return 0
+		else
+			echo "failure"
+			return 1
+		fi
+	fi
+        echo
+}
+
 # Start a module
 sympa_module_start() {
     if [ $# = 0 ] ; then
@@ -225,6 +243,7 @@ case "$1" in
   start)
 	if [ ! -f ${sympalockdir}/sympa ]; then
 		echo "Starting Sympa subsystem: "
+		sympa_check || exit 1
 		sympa_start sympa
 		sympa_start spooler
 		sympa_start bulk
