[svn] retrieving lmatest modifications from 6.1 branch.
git-svn-id: https://subversion.renater.fr/sympa/trunk@6434 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce

diff --git a/po/Makefile.in.in b/po/Makefile.in.in
--- a/po/Makefile.in.in
+++ b/po/Makefile.in.in
@@ -56,6 +56,8 @@ XGETTEXT = ./xgettext.pl
 MSGMERGE = msgmerge
 MSGMERGE_UPDATE = @MSGMERGE@ --update
 MSGCAT = msgcat
+MSGATTRIB = msgattrib
+MSGEN = msgen
 MSGINIT = msginit
 MSGCONV = msgconv
 MSGFILTER = msgfilter
@@ -363,15 +365,21 @@ update-po: Makefile
 	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
 	echo "$${cdcmd}$(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
 	cd $(srcdir); \
-	if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
-	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
-	    rm -f $$tmpdir/$$lang.new.po; \
+	if test "$$lang" = "en_US"; then\
+          $(MSGEN) -o $$tmpdir/$$lang.new.po $(DOMAIN).pot; \
+        else \
+	  if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
+	    :; \
 	  else \
-            $(MSGCAT) --use-first -o $$tmpdir/$$lang.new.po $$tmpdir/$$lang.new.po $$lang.po; \
-	  fi; \
-	else \
-	  echo "msgmerge for $$lang.po failed!" 1>&2; \
+	    echo "msgmerge for $$lang.po failed!" 1>&2; \
+            cp -p $$lang.po $$tmpdir/$$lang.new.po;\
+	  fi;\
 	fi;\
+	if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	  rm -f $$tmpdir/$$lang.new.po; \
+	else \
+          $(MSGCAT) --use-first -o $$tmpdir/$$lang.po $$tmpdir/$$lang.new.po $$lang.po; \
+	fi; \
         rm -f $$tmpdir/$$lang.new.po;
 
 
@@ -413,23 +421,35 @@ clean-po:
 	  test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
 	  echo "$${cdcmd}$(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
 	  cd $(srcdir); \
-	  if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
-	    if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
-	      rm -f $$tmpdir/$$lang.new.po; \
-	    else \
-	      if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
-	        :; \
+	  if test "$$lang" = "en_US"; then\
+	    if $(MSGATTRIB) --no-fuzzy -o $$tmpdir/$$lang.previous.po $$lang.po; then \
+	      if cmp $$lang.po $$tmpdir/$$lang.previous.po >/dev/null 2>&1; then \
+	        rm -f $$tmpdir/$$lang.new.po; \
 	      else \
-	        echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
-	        exit 1; \
+                $(MSGEN) -o $$tmpdir/$$lang.new.po $(DOMAIN).pot; \
+                $(MSGCAT) --use-first -o $$tmpdir/$$lang.new.po $$lang.po $$tmpdir/$$lang.new.po; \
 	      fi; \
-	    fi; \
-	  else \
-	    echo "msgmerge for $$lang.po failed!" 1>&2; \
-	    rm -f $$tmpdir/$$lang.new.po; \
+	    else \
+	      echo "Could not gather not fuzzy translated strings in en_US.po" 1>&2; \
+	    fi;\
+          else \
+	    if $(MSGMERGE) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
+	      if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	        rm -f $$tmpdir/$$lang.new.po; \
+	      else \
+	        if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
+	          :; \
+	        else \
+	          echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
+	          exit 1; \
+	        fi; \
+	      fi; \
+	    else \
+	      echo "msgmerge for $$lang.po failed!" 1>&2; \
+	      rm -f $$tmpdir/$$lang.new.po; \
+	    fi;\
 	  fi;\
         done;\
-        msgen en_US.po -o en_US.po;\
 
 
 $(DUMMYPOFILES):
